"""data-src/*.json  →  data/*.js  (the window.*_DATA globals the pages read)

Sources (all JSON, public conference data + this site's Chinese text):
  papers.json, schedule.json, workshops.json   — collected from colm.cc / workshop sites
  topics.json                                   — the 17 call-for-papers areas
  zh.json                                       — hand-written Chinese for workshops / schedule / labels
  papers-zh.json                                — Chinese titles + abstracts   {id: {title, abstract}}
  papers-topics.json                            — topic per paper              {id: topic-id}

Outputs:
  data/papers.js                 window.PAPERS_DATA  (core fields, no abstracts)
  data/papers-abstracts.en.js    window.PAPERS_ABSTRACTS  {id: abstract}   (lazy-loaded)
  data/papers-abstracts.zh.js    window.PAPERS_ABSTRACTS  {id: abstract}   (lazy-loaded)
  data/schedule.js               window.SCHEDULE_DATA
  data/workshops.js              window.WORKSHOPS_DATA

Usage:  uv run python scripts/build_data.py [--src data-src] [--out .]
"""
from __future__ import annotations

import argparse
import json
import re
from datetime import datetime, timezone
from pathlib import Path


def repo_root() -> Path:
    p = Path(__file__).resolve()
    for parent in [p] + list(p.parents):
        if (parent / ".git").exists():
            return parent
    return p.parents[1]


ROOT = repo_root()

BANNER = """/* Generated by scripts/build_data.py — do not edit by hand.
   Sources: colm.cc (schedule, accepted papers), OpenReview (keywords), workshop websites.
   Chinese text is this site's own translation. Content © the respective authors / COLM organizers. */
"""


def hhmm(printed: str | None) -> str | None:
    """'11:00 AM PDT' → '11:00'; '4:40 PM PDT' → '16:40'; 'HH:MM' passes through."""
    if not printed:
        return None
    m = re.match(r"^\s*(\d{1,2}):(\d{2})\s*([AP]M)?", printed, re.I)
    if not m:
        return printed
    h, mi, ap = int(m.group(1)), m.group(2), (m.group(3) or "").upper()
    if ap == "PM" and h != 12:
        h += 12
    if ap == "AM" and h == 12:
        h = 0
    return f"{h:02d}:{mi}"


def bi(en, zh) -> dict | None:
    if en is None:
        return None
    return {"en": en, "zh": zh or en}


def load(src: Path, name: str, default=None):
    f = src / name
    if not f.exists():
        return default
    return json.loads(f.read_text(encoding="utf-8"))


def dump_js(name: str, obj, dest: Path) -> int:
    dest.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(obj, ensure_ascii=False, separators=(",", ":"))
    dest.write_text(f"{BANNER}window.{name} = {body};\n", encoding="utf-8")
    return dest.stat().st_size


# ---------------------------------------------------------------- papers
def build_papers(src: Path, out: Path, zh: dict) -> dict:
    raw = load(src, "papers.json", [])
    topics = load(src, "topics.json", [])
    zh_papers = load(src, "papers-zh.json", {})
    topic_of = load(src, "papers-topics.json", {})
    papers, abs_en, abs_zh, by_colm_id = [], {}, {}, {}
    for p in raw:
        z = zh_papers.get(p["id"]) or {}
        papers.append({
            "id": p["id"],
            "title": p["title"],
            "titleZh": z.get("title"),
            "authors": p["authors"],
            "affiliations": p.get("affiliations"),
            "topic": topic_of.get(p["id"]),
            "oral": bool(p.get("oral")),
            "oralSession": p.get("oralSession"),
            "oralTime": hhmm(p.get("oralTime")),
            "oralRoom": p.get("oralRoom"),
            "posterSession": p.get("posterSession"),
            "day": p.get("day"),
            "time": hhmm(p.get("time")),
            "room": p.get("room"),
            "posterNumber": p.get("posterNumber"),
            "links": {k: v for k, v in (p.get("links") or {}).items() if v},
        })
        if p.get("abstract"):
            abs_en[p["id"]] = p["abstract"]
        if z.get("abstract"):
            abs_zh[p["id"]] = z["abstract"]
        if p.get("colmId") is not None:
            by_colm_id[p["colmId"]] = p["id"]
    data = {
        "meta": {"source": "colm.cc + OpenReview", "generated": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
                 "total": len(papers), "oral": sum(1 for p in papers if p["oral"]),
                 "withTopic": sum(1 for p in papers if p["topic"]), "withTitleZh": sum(1 for p in papers if p["titleZh"])},
        "topics": [{"id": t["id"], "en": t["en"], "zh": t["zh"]} for t in topics],
        "papers": papers,
    }
    size = dump_js("PAPERS_DATA", data, out / "data/papers.js")
    s_en = dump_js("PAPERS_ABSTRACTS", abs_en, out / "data/papers-abstracts.en.js")
    s_zh = dump_js("PAPERS_ABSTRACTS", abs_zh if abs_zh else abs_en, out / "data/papers-abstracts.zh.js")
    return {"count": len(papers), "bytes": size, "absEn": (len(abs_en), s_en), "absZh": (len(abs_zh), s_zh),
            "withTopic": data["meta"]["withTopic"], "withTitleZh": data["meta"]["withTitleZh"], "byColmId": by_colm_id}


# ---------------------------------------------------------------- workshops
def build_workshops(src: Path, out: Path, zh: dict) -> dict:
    raw = load(src, "workshops.json", [])
    desc_zh = zh.get("workshopDescriptions", {})
    dl_zh = zh.get("deadlineLabels", {})
    items = []
    for w in raw:
        items.append({
            "id": w["id"], "name": w["name"], "shortName": w.get("shortName"), "edition": w.get("edition"),
            "contact": w.get("contact"), "organizers": w.get("organizers"),
            "date": w["date"], "startTime": hhmm(w.get("startTime")), "endTime": hhmm(w.get("endTime")),
            "room": w.get("room"), "website": w.get("website"), "colmUrl": w.get("colmUrl"),
            "description": bi(w.get("description"), desc_zh.get(w["id"])),
            "topics": w.get("topics"),
            "schedule": [{"time": s.get("time"), "title": s.get("title"), "speaker": s.get("speaker")} for s in (w.get("schedule") or [])] or None,
            "speakers": w.get("speakers"),
            "deadlines": [{"label": bi(d.get("label"), dl_zh.get(d.get("label"))), "date": d.get("date"), "note": d.get("note")} for d in (w.get("deadlines") or [])] or None,
            "links": {k: v for k, v in (w.get("links") or {}).items() if v},
        })
    size = dump_js("WORKSHOPS_DATA", {"workshops": items}, out / "data/workshops.js")
    return {"count": len(items), "bytes": size, "byColmUrl": {w["colmUrl"]: w for w in items if w.get("colmUrl")}}


# ---------------------------------------------------------------- schedule
def title_zh(title: str, typ: str, zh: dict) -> str:
    pats, fixed = zh.get("sessionPatterns", {}), zh.get("sessionTitles", {})
    if title in fixed:
        return fixed[title]
    for pat, key, arg in ((r"^Keynote:\s*(.+)$", "keynote", "name"), (r"^Oral Session\s+(\d+)$", "oral", "n"),
                          (r"^Poster Session\s+(\d+)$", "poster", "n"), (r"^Panel:\s*(.+)$", "panel", "names")):
        m = re.match(pat, title)
        if m and key in pats:
            return pats[key].format(**{arg: m.group(1)})
    return title


def build_schedule(src: Path, out: Path, zh: dict, paper_ids: dict, workshops_by_url: dict) -> dict:
    raw = load(src, "schedule.json", {"days": [], "keyDates": []})
    days = []
    for d in raw["days"]:
        if d["date"] == "2026-10-05":           # registration desk only
            continue
        sessions, block = [], None
        for s in d["sessions"]:
            if s["type"] == "workshop":
                w = workshops_by_url.get(s.get("colmUrl"))
                if block is None:
                    block = {"id": "workshops", "start": s["start"], "end": s["end"], "type": "workshop",
                             "title": {"en": "Workshops (18 in parallel)", "zh": zh.get("sessionPatterns", {}).get("workshops", "Workshops")},
                             "room": None, "speaker": None, "papers": None, "paperCount": None, "rooms": None,
                             "colmUrl": "https://colm.cc/virtual/2026/events/workshop",
                             "notes": bi("Rooms not published on colm.cc yet.", zh.get("sessionNotes", {}).get("Rooms not published on colm.cc yet.")),
                             "workshops": []}
                block["workshops"].append({"id": w["id"] if w else s["id"], "name": s["title"], "room": s.get("room")})
                continue
            papers = [{"title": p["title"], "authors": p.get("authors"), "start": p.get("start"),
                       "paperId": paper_ids.get(p.get("paperId")), "colmUrl": p.get("colmUrl")} for p in s["papers"]] if s.get("papers") else None
            sessions.append({
                "id": s["id"], "start": s["start"], "end": s.get("end"), "type": s["type"],
                "title": {"en": s["title"], "zh": title_zh(s["title"], s["type"], zh)},
                "room": s.get("room"), "speaker": s.get("speaker"), "panelists": s.get("panelists"),
                "papers": papers, "paperCount": s.get("paperCount"),
                "rooms": s.get("rooms"), "roomAssignments": s.get("roomAssignments"), "colmUrl": s.get("colmUrl"),
                "notes": bi(s.get("notes"), zh.get("sessionNotes", {}).get(s.get("notes"))) if s.get("notes") and s["type"] in ("keynote", "panel") else None,
            })
        if block:
            sessions.insert(1 if sessions else 0, block)
        days.append({"date": d["date"], "weekday": d.get("weekday"),
                     "label": {"en": d["label"], "zh": zh.get("dayLabels", {}).get(d["label"], d["label"])},
                     "sessions": sessions})
    key_dates = [{"group": {"en": k["group"], "zh": zh.get("keyDateGroups", {}).get(k["group"], k["group"])},
                  "label": {"en": k["label"], "zh": zh.get("keyDateLabels", {}).get(k["label"], k["label"])},
                  "date": k.get("date"), "time": k.get("time"), "timezone": k.get("timezone"), "note": None}
                 for k in raw["keyDates"]]
    v = raw.get("venue") or {}
    data = {"timezone": raw.get("timezone", "America/Los_Angeles"),
            "venue": {"name": v.get("shortName") or v.get("name"), "fullName": v.get("name"), "city": v.get("city"),
                      "address": v.get("address"), "url": v.get("url"), "mapsUrl": v.get("mapsUrl")},
            "days": days, "keyDates": key_dates}
    size = dump_js("SCHEDULE_DATA", data, out / "data/schedule.js")
    return {"days": len(days), "sessions": sum(len(d["sessions"]) for d in days), "bytes": size}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="data-src")
    ap.add_argument("--out", default=".")
    a = ap.parse_args()
    src = (ROOT / a.src) if not Path(a.src).is_absolute() else Path(a.src)
    out = (ROOT / a.out) if not Path(a.out).is_absolute() else Path(a.out)
    zh = load(src, "zh.json", {})
    p = build_papers(src, out, zh)
    w = build_workshops(src, out, zh)
    s = build_schedule(src, out, zh, p["byColmId"], w["byColmUrl"])
    print(f"papers.js              {p['count']} papers, {p['bytes']/1024:.0f} KB  (topic {p['withTopic']}, zh title {p['withTitleZh']})")
    print(f"papers-abstracts.en.js {p['absEn'][0]} abstracts, {p['absEn'][1]/1024:.0f} KB")
    print(f"papers-abstracts.zh.js {p['absZh'][0]} abstracts, {p['absZh'][1]/1024:.0f} KB")
    print(f"workshops.js           {w['count']} workshops, {w['bytes']/1024:.0f} KB")
    print(f"schedule.js            {s['days']} days / {s['sessions']} sessions, {s['bytes']/1024:.0f} KB")


if __name__ == "__main__":
    main()
